name: Deploy Angular to Vercel

on:
  push:
    branches:
      - main # change if your main branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Angular 16+ uses Node 18

      - name: Install dependencies
        run: npm ci

      #   - name: Lint
      #     run: npm run lint

      #   - name: Run tests
      #     run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
